### PR TITLE
Fixed compiler warnings

### PR DESCRIPTION
**Pull request by kaminoo**
Properly using the compiler constants

### CODE REVIEW

**Comment by santigimeno** [comment]
@kaminoo thanks for the PR's
A couple of questions:
- What's your environment? Can you paste the warnings you're seeing?
- I'm not sure the change is correct. From the windows and pcsclite documentation([1] and [2]), `SCardEstablishContext` returns `LONG`

[1] https://msdn.microsoft.com/en-us/library/windows/desktop/aa379479%28v=vs.85%29.aspx
[2] https://pcsclite.alioth.debian.org/api/group__API.html#gaa1b8970169fd4883a6dc4a8f43f19b67

**Comment by kaminoo** [comment]
Hi.
I'm on OSX Yosemite on a 64bit machine.
You are correct, the result should be a LONG.
Seems there's a simple printf problem, but the other two look like the contacts to which result compares are not declared as LONG but ULONG. Weird.

Ideas?

Here's the node-gyp rebuild complete output:

node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.0.3
gyp info using node@4.0.0 | darwin | x64
gyp info spawn python
gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/sebastianarena/Developer/Tools/node-pcsclite/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/sebastianarena/.node-gyp/4.0.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/sebastianarena/.node-gyp/4.0.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/sebastianarena/Developer/Tools/node-pcsclite',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/pcsclite/src/addon.o
  CXX(target) Release/obj.target/pcsclite/src/pcsclite.o
In file included from ../src/pcsclite.cpp:2:
../src/common.h:46:18: warning: format specifies type 'unsigned long' but the argument has type 'LONG' (aka 'int') [-Wformat]
                 result);
                 ^~~~~~
../src/pcsclite.cpp:45:52: warning: comparison of integers of different signs: 'LONG' (aka 'int') and 'unsigned int' [-Wsign-compare]
        if ((result != SCARD_S_SUCCESS) && (result != SCARD_E_TIMEOUT)) {
                                            ~~~~~~ ^  ~~~~~~~~~~~~~~~
../src/pcsclite.cpp:165:20: warning: comparison of integers of different signs: 'LONG' (aka 'int') and 'unsigned int' [-Wsign-compare]
        if (result == SCARD_E_NO_READERS_AVAILABLE) {
            ~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
3 warnings generated.
  CXX(target) Release/obj.target/pcsclite/src/cardreader.o
In file included from ../src/cardreader.cpp:2:
../src/common.h:46:18: warning: format specifies type 'unsigned long' but the argument has type 'LONG' (aka 'int') [-Wformat]
                 result);
                 ^~~~~~
1 warning generated.
  SOLINK_MODULE(target) Release/pcsclite.node
gyp info ok

**Comment by santigimeno** [comment]
Thanks for the info.
It looks like the problem comes from the fact that `LONG` in `OSX` is defined as `int32_t` whereas in Linux is defined as an `unsigned int`

**Comment by santigimeno** [comment]
Sorry, I meant that in `Linux` can be defined as `long int`

**Comment by santigimeno** [comment]
So I think that removing the long modifier in the `snprintf` @ `common.h` could fix a couple of those warnings

**Comment by kaminoo** [comment]
Yes, two of them.
But I'm more worried about the other ones. The ones where result is compared to a defined constant which are said to be `unsigned long` instead of `LONG`. I find that really disturbing.
But I still believe the problem is with OSX and 32/64 bit architectures.
I found a couple of sites explaining that using `LONG` might not be the best since it can vary from 4bytes to 8bytes depending on the architecture. The best way is using `int` that is always 4bytes or `long long` that is always 8bytes.

What do you think we should do?

[1] https://software.intel.com/en-us/articles/size-of-long-integer-type-on-different-architecture-and-os
[2] https://developer.apple.com/library/mac/documentation/Darwin/Conceptual/64bitPorting/transition/transition.html

**Comment by LudovicRousseau** [comment]
On Linux and Windows ``SCardEstablishContext()`` returns a LONG
On Mac OS X ``SCardEstablishContext()`` returns a int32_t
You should use ``"%ld"`` on Linux and Windows, and ``"%d"`` on Mac OS X (or equivalent). Or just ignore compiler warnings on some plateform(s).

On Linux and Windows LONG is defined as: ``typedef long LONG;``
But on a 64 bits CPU a long is 64 bits on Linux (LP) but only 32 bits on Windows (LLP).
https://en.wikipedia.org/wiki/64-bit_computing#64-bit_data_models

Yes, it is complex.

**Comment by santigimeno** [comment]
That was helpful. Thanks Ludovic!

**Comment by santigimeno** [comment]
@kaminoo Can you check if https://github.com/santigimeno/node-pcsclite/pull/44 fixes the warnings for you?

**Comment by kaminoo** [comment]
@santigimeno yes, #44 compiles without any warnings. Great job.

**Comment by santigimeno** [comment]
Fixed by https://github.com/santigimeno/node-pcsclite/commit/1ca9670420d638a89876ad026bef1425a2c8d526 https://github.com/santigimeno/node-pcsclite/commit/83be0bdf61588e413e03d5edbd6c68c98a53037f

**Pull request closed without merging**
