### PR TITLE
Support Windows

### PR DESCRIPTION
**Pull request by santigimeno**
- Migrate pthreads to uv_threads.
- Cross platform implementation of sleep, snprintf and error_msg.

### CODE REVIEW

**Comment by santigimeno** [comment]
I'd like to make a `0.4.0` in a few days with these changes. I would really appreciate if you could make some testing basically to know that nothing is broken, specially on Windows, as I don't have access to any machine. Thanks in advance!!

/cc @LudovicRousseau @oliversalzburg @f0zi @marcos9966

**Comment by marcos9966** [comment]
I will try as soon as possible.
    
                         Thanks, Marcos
    
    
    On 22/05/2015 15:20, Santiago Gimeno
      wrote:
    
    
      I'd like to make a 0.4.0 in a few days with these
        changes. I would really appreciate if you could make some
        testing basically to know that nothing is broken, specially on
        Windows, as I don't have access to any machine. Thanks in
        advance!!
      /cc @LudovicRousseau
        @oliversalzburg
        @f0zi @marcos9966
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by oliversalzburg** [comment]
Same here. I'll try to get to it during this week at work. Thanks for your effort! :)

**Comment by f0zi** [comment]
I found some problems (easy to fix), but I'm unable to run the examples or your test in node.js (remember I'm using Electron). I'll push my changes  but I might not be able to spend too much time doing testing in node.js today.

**Comment by f0zi** [comment]
69061314c076b240cdbb06abf2c26cde1c35cf99

**Comment by santigimeno** [comment]
@f0zi Thanks a lot! Branch updated with your changes.

**Comment by santigimeno** [comment]
Thanks to all for taking the time!

**Comment by oliversalzburg** [comment]
First of all the output:

```shell
OliverSalzburg@OLIVER-PC /d/node-pcsclite/examples (windows)
$ node example.js
New reader detected OMNIKEY CardMan 5x21 0
New reader detected OMNIKEY CardMan 5x21-CL 0
Status( OMNIKEY CardMan 5x21 0 ): { state: 18, atr: <Buffer > }
card removed
Disconnected
Status( OMNIKEY CardMan 5x21-CL 0 ): { state: 131090, atr: <Buffer > }
card removed
Disconnected
Status( OMNIKEY CardMan 5x21-CL 0 ): { state: 196642,
  atr: <Buffer 3b 8f 80 01 80 4f 0c a0 00 00 03 06 03 00 01 00 00 00 00 6a> }
card inserted
Status( OMNIKEY CardMan 5x21-CL 0 ): { state: 196898,
  atr: <Buffer 3b 8f 80 01 80 4f 0c a0 00 00 03 06 03 00 01 00 00 00 00 6a> }
Protocol( OMNIKEY CardMan 5x21-CL 0 ): 2
[Error: SCardTransmit error: A device attached to the system is not functioning.
(0x0000001f)]
Status( OMNIKEY CardMan 5x21-CL 0 ): { state: 262162, atr: <Buffer > }
card removed
Disconnected
Status( OMNIKEY CardMan 5x21-CL 0 ): { state: 327714,
  atr: <Buffer 3b 8f 80 01 80 4f 0c a0 00 00 03 06 03 00 01 00 00 00 00 6a> }
card inserted
Status( OMNIKEY CardMan 5x21-CL 0 ): { state: 327970,
  atr: <Buffer 3b 8f 80 01 80 4f 0c a0 00 00 03 06 03 00 01 00 00 00 00 6a> }
Protocol( OMNIKEY CardMan 5x21-CL 0 ): 2
[Error: SCardTransmit error: A device attached to the system is not functioning.
(0x0000001f)]
Status( OMNIKEY CardMan 5x21-CL 0 ): { state: 393234, atr: <Buffer > }
card removed
Disconnected
```
 What you see are two reads of the same card. I'm not sure what the error is about.

**Comment by santigimeno** [comment]
@oliversalzburg I'm not sure there's something wrong in there. It looks like there are 2 readers, which makes sense for a CardMan 5x21 reader. The errors are probably returned because the transmitted is just wrong?. Could you transmit something like this and see how it goes?:
```
reader.transmit(new Buffer([0xFF, 0xCA, 0x00, 0x00, 0x00]), 40, protocol, function(err, data) {
```

**Comment by oliversalzburg** [comment]
@santigimeno Yes, there being 2 readers is definitely expected. I'm only using the CL one though.

With the line you gave me, I get the following output instead. This time I was only scanning once:

```shell
OliverSalzburg@OLIVER-PC /d/node-pcsclite/examples (windows)
$ node example.js
New reader detected OMNIKEY CardMan 5x21 0
New reader detected OMNIKEY CardMan 5x21-CL 0
Status( OMNIKEY CardMan 5x21 0 ): { state: 18, atr: <Buffer > }
card removed
Disconnected
Status( OMNIKEY CardMan 5x21-CL 0 ): { state: 524306, atr: <Buffer > }
card removed
Disconnected
Status( OMNIKEY CardMan 5x21-CL 0 ): { state: 589858,
  atr: <Buffer 3b 8f 80 01 80 4f 0c a0 00 00 03 06 03 00 01 00 00 00 00 6a> }
card inserted
Status( OMNIKEY CardMan 5x21-CL 0 ): { state: 590114,
  atr: <Buffer 3b 8f 80 01 80 4f 0c a0 00 00 03 06 03 00 01 00 00 00 00 6a> }
Protocol( OMNIKEY CardMan 5x21-CL 0 ): 2
Data received <Buffer 7c c6 ef 06 90 00>
Reader OMNIKEY CardMan 5x21-CL 0 removed
```

The UID of the card is 7CC6EF06. So that seems to be working.

**Comment by santigimeno** [comment]
@oliversalzburg That's great news! Thanks for helping :)

**Comment by oliversalzburg** [comment]
Well, thank *you* for taking the time to fix up a Windows build :)

**Comment by santigimeno** [comment]
Merged and published in version 0.4.0

**Comment by santigimeno** [comment]
Thanks a lot for the help!

**Pull request closed without merging**
